// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/warehouse_revamp/backend/services/user_service/user_v1"
)

// Injectors from wire.go:

// InitializeSan is the operations tool's composition root. Regenerate after changing it:
//
//	go tool wire ./tools/san
//
// The DSN is a PARAMETER, not a provider: the operator picks the database per invocation (see
// withSan), and everything downstream — the pool, the resolver, the service — is built for that
// choice.
func InitializeSan(dsn DatabaseDSN) (*San, error) {
	db, err := NewDatabase(dsn)
	if err != nil {
		return nil, err
	}
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	signer := NewSigner(config)
	cacheManager := NewCache(config)
	roleResolver := NewRoleResolver(db, cacheManager)
	mainInternalHTTPClient := NewInternalHTTPClient()
	teamServiceClient := NewTeamClient(config, mainInternalHTTPClient)
	service := user_v1.NewService(db, signer, roleResolver, teamServiceClient, cacheManager)
	san := NewSan(db, service)
	return san, nil
}
