// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/warehouse_revamp/backend/services/product_service/product_v1"
	"github.com/pdcgo/warehouse_revamp/backend/services/shipping_service/shipping_v1"
	"github.com/pdcgo/warehouse_revamp/backend/services/team_service/team_v1"
	"github.com/pdcgo/warehouse_revamp/backend/services/user_service/user_v1"
)

// Injectors from wire.go:

// InitializeApp is the composition root. Regenerate after changing it:
//
//	cd backend && go tool wire ./cmd/app_development
func InitializeApp() (*App, error) {
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(config)
	if err != nil {
		return nil, err
	}
	signer := NewSigner(config)
	cacheManager := NewCache(config)
	roleResolver := NewRoleResolver(db, cacheManager)
	otpVerification := NewOtp(config)
	authService := user_v1.NewAuthService(db, signer, roleResolver, otpVerification)
	mainInternalHTTPClient := NewInternalHTTPClient()
	teamServiceClient := NewTeamClient(config, mainInternalHTTPClient)
	service := user_v1.NewService(db, signer, roleResolver, teamServiceClient, cacheManager)
	userServiceClient := NewUserClient(config, mainInternalHTTPClient)
	team_v1Service := team_v1.NewService(db, userServiceClient)
	shipping_v1Service := shipping_v1.NewService(db)
	product_v1Service := product_v1.NewService(db)
	serveMux, err := NewServeMux(authService, service, team_v1Service, shipping_v1Service, product_v1Service, roleResolver, signer)
	if err != nil {
		return nil, err
	}
	server := NewServer(config, serveMux)
	app := NewApp(server)
	return app, nil
}
